name: Java CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Build with Maven and push to docker hub
        run: mvn compile jib:build -Djib.to.auth.username=${{ secrets.DOCKER_HUB_LOGIN }} -Djib.to.auth.password=${{ secrets.DOCKER_HUB_PASSWORD }}
